import type { Metadata } from "next";
import React from "react";
import HeaderSection from "./(common)/header/page";
import FooterSection from "./(common)/footer/page";
import AnnouncementSection from "./(common)/announcement/page";

export const metadata: Metadata = {
  title: "Compliance Foundry Website",
  description: "Generated by create next app",
  keywords: [
    "Compliance",
    "Risk Management",
    "Policy Automation",
    "Regulatory Framework",
    "Governance",
    "Enterprise Compliance",
    "Audit Tools",
    "Compliance Software",
    "Corporate Risk",
    "Compliance Foundry",
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode;

  footer: React.ReactNode;
}>) {
  // const res = await fetch("https://your-api.com/announcement-status");
  // const data = await res.json();
  const showAnnouncement = true;
  return (
    <html lang="en">
      <body>
        <HeaderSection />
        {showAnnouncement && <AnnouncementSection />}
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
