import type { Metadata } from "next";
import React from "react";
import HeaderSection from "./(common)/header/page";
import FooterSection from "./(common)/footer/page";
import AnnouncementSection from "./(common)/announcement/page";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata: Metadata = {
  title: "Compliance Foundry Website",
  description: "Generated by create next app",
  keywords: [
    "Compliance",
    "Risk Management",
    "Policy Automation",
    "Regulatory Framework",
    "Governance",
    "Enterprise Compliance",
    "Audit Tools",
    "Compliance Software",
    "Corporate Risk",
    "Compliance Foundry",
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode;

  footer: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body>
         <AnnouncementSection />
        <HeaderSection />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
